
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load secrets from .env.local (Next.js's local secrets file). dotenv's default
// "dotenv/config" only reads .env, so we load .env.local explicitly here so the
// Prisma CLI sees the same DATABASE_URL / DIRECT_URL the Next.js app uses.
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig, env } from "prisma/config";

// The "classic" engine reads its connection from THIS datasource block (it does
// not fall back to the schema's datasource for the actual connection). We give it
// BOTH urls: `directUrl` (DIRECT_URL → 5432 session pooler) is used for
// migrations, which need a real session for advisory locks; `url` (DATABASE_URL →
// 6543 transaction pooler) is the runtime/pooled connection.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    directUrl: env("DIRECT_URL"),
  },
});
